# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab237c04e39d5da85267e7f36a13694fbc610740a1a700e0241d4a2ee19666df37dc4d41f3e47a28ba1f092126cd8d8b7e8e24b609539f4d358afd6ca6fde5a7

test:
  secret_key_base: 44ad8ed672ae2631f0262e314dfd21d06f96072d660efa90068e9f9d540804b6deefa3c68f87ffa14e310edc43d93aa44d372ece5e189a1f18c563d9416e5e57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
